//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 8 images.
  struct image {
    /// Image `emptyCoin`.
    static let emptyCoin = Rswift.ImageResource(bundle: R.hostingBundle, name: "emptyCoin")
    /// Image `ic_back`.
    static let ic_back = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_back")
    /// Image `ic_close`.
    static let ic_close = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_close")
    /// Image `ic_filter`.
    static let ic_filter = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_filter")
    /// Image `ic_menuHome`.
    static let ic_menuHome = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_menuHome")
    /// Image `ic_menu`.
    static let ic_menu = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_menu")
    /// Image `ic_more`.
    static let ic_more = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_more")
    /// Image `ic_wallet`.
    static let ic_wallet = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_wallet")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "emptyCoin", bundle: ..., traitCollection: ...)`
    static func emptyCoin(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.emptyCoin, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "ic_back", bundle: ..., traitCollection: ...)`
    static func ic_back(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_back, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "ic_close", bundle: ..., traitCollection: ...)`
    static func ic_close(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_close, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "ic_filter", bundle: ..., traitCollection: ...)`
    static func ic_filter(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_filter, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "ic_menu", bundle: ..., traitCollection: ...)`
    static func ic_menu(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_menu, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "ic_menuHome", bundle: ..., traitCollection: ...)`
    static func ic_menuHome(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_menuHome, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "ic_more", bundle: ..., traitCollection: ...)`
    static func ic_more(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_more, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "ic_wallet", bundle: ..., traitCollection: ...)`
    static func ic_wallet(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_wallet, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    /// This `R.string.accessibility` struct is generated, and contains static references to 4 localization keys.
    struct accessibility {
      /// Value: Asset Cell
      static let assetCell = Rswift.StringResource(key: "assetCell", tableName: "Accessibility", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Asset Detail
      static let assetDetail = Rswift.StringResource(key: "assetDetail", tableName: "Accessibility", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Asset List
      static let assetList = Rswift.StringResource(key: "assetList", tableName: "Accessibility", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Navigation View
      static let navigationApplicaton = Rswift.StringResource(key: "navigationApplicaton", tableName: "Accessibility", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: Asset Cell
      static func assetCell(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("assetCell", tableName: "Accessibility", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Accessibility", preferredLanguages: preferredLanguages) else {
          return "assetCell"
        }

        return NSLocalizedString("assetCell", tableName: "Accessibility", bundle: bundle, comment: "")
      }

      /// Value: Asset Detail
      static func assetDetail(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("assetDetail", tableName: "Accessibility", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Accessibility", preferredLanguages: preferredLanguages) else {
          return "assetDetail"
        }

        return NSLocalizedString("assetDetail", tableName: "Accessibility", bundle: bundle, comment: "")
      }

      /// Value: Asset List
      static func assetList(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("assetList", tableName: "Accessibility", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Accessibility", preferredLanguages: preferredLanguages) else {
          return "assetList"
        }

        return NSLocalizedString("assetList", tableName: "Accessibility", bundle: bundle, comment: "")
      }

      /// Value: Navigation View
      static func navigationApplicaton(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("navigationApplicaton", tableName: "Accessibility", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Accessibility", preferredLanguages: preferredLanguages) else {
          return "navigationApplicaton"
        }

        return NSLocalizedString("navigationApplicaton", tableName: "Accessibility", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.app` struct is generated, and contains static references to 20 localization keys.
    struct app {
      /// en translation: An unexpected error has occurred.
      ///
      /// Locales: en, pt-BR
      static let other = Rswift.StringResource(key: "other", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: An unexpected error occurred while communicating with the server.
      ///
      /// Locales: en, pt-BR
      static let mapping = Rswift.StringResource(key: "mapping", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: First negotiation
      ///
      /// Locales: en, pt-BR
      static let firstNegotiation = Rswift.StringResource(key: "firstNegotiation", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: First purchase order
      ///
      /// Locales: en, pt-BR
      static let firstPurchaseOrder = Rswift.StringResource(key: "firstPurchaseOrder", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: First quotation
      ///
      /// Locales: en, pt-BR
      static let firstQuotation = Rswift.StringResource(key: "firstQuotation", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: Last negotiation
      ///
      /// Locales: en, pt-BR
      static let lastNegotiation = Rswift.StringResource(key: "lastNegotiation", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: Last purchase order
      ///
      /// Locales: en, pt-BR
      static let lastPurchaseOrder = Rswift.StringResource(key: "lastPurchaseOrder", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: Last quotation
      ///
      /// Locales: en, pt-BR
      static let lastQuotation = Rswift.StringResource(key: "lastQuotation", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: Overview
      ///
      /// Locales: en, pt-BR
      static let homeTitle = Rswift.StringResource(key: "homeTitle", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: Please try again later.
      ///
      /// Locales: en
      static let apiNotAvailable = Rswift.StringResource(key: "apiNotAvailable", tableName: "App", bundle: R.hostingBundle, locales: ["en"], comment: nil)
      /// en translation: Sum of an Hour
      ///
      /// Locales: en, pt-BR
      static let sumAnHour = Rswift.StringResource(key: "sumAnHour", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: Sum of an day
      ///
      /// Locales: en, pt-BR
      static let sumAnday = Rswift.StringResource(key: "SumAnday", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: Summation one month
      ///
      /// Locales: en, pt-BR
      static let sumMonth = Rswift.StringResource(key: "SumMonth", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: Total symbols
      ///
      /// Locales: en, pt-BR
      static let totalSymbols = Rswift.StringResource(key: "totalSymbols", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: Transfer coins from other platforms   to your bitcoin market wallet or   access the site and make a deposit.
      ///
      /// Locales: en, pt-BR
      static let messageHomeHeader = Rswift.StringResource(key: "messageHomeHeader", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: You are currently offline.
      ///
      /// Locales: en, pt-BR
      static let offline = Rswift.StringResource(key: "offline", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: You have no balance
      ///
      /// Locales: en, pt-BR
      static let titleHomeHeader = Rswift.StringResource(key: "titleHomeHeader", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: erro
      ///
      /// Locales: en, pt-BR
      static let error = Rswift.StringResource(key: "error", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: price: 
      ///
      /// Locales: en, pt-BR
      static let price = Rswift.StringResource(key: "price", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)
      /// en translation: show details
      ///
      /// Locales: en, pt-BR
      static let showDetails = Rswift.StringResource(key: "showDetails", tableName: "App", bundle: R.hostingBundle, locales: ["en", "pt-BR"], comment: nil)

      /// en translation: An unexpected error has occurred.
      ///
      /// Locales: en, pt-BR
      static func other(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("other", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "other"
        }

        return NSLocalizedString("other", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: An unexpected error occurred while communicating with the server.
      ///
      /// Locales: en, pt-BR
      static func mapping(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("mapping", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "mapping"
        }

        return NSLocalizedString("mapping", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: First negotiation
      ///
      /// Locales: en, pt-BR
      static func firstNegotiation(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("firstNegotiation", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "firstNegotiation"
        }

        return NSLocalizedString("firstNegotiation", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: First purchase order
      ///
      /// Locales: en, pt-BR
      static func firstPurchaseOrder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("firstPurchaseOrder", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "firstPurchaseOrder"
        }

        return NSLocalizedString("firstPurchaseOrder", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: First quotation
      ///
      /// Locales: en, pt-BR
      static func firstQuotation(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("firstQuotation", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "firstQuotation"
        }

        return NSLocalizedString("firstQuotation", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: Last negotiation
      ///
      /// Locales: en, pt-BR
      static func lastNegotiation(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("lastNegotiation", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "lastNegotiation"
        }

        return NSLocalizedString("lastNegotiation", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: Last purchase order
      ///
      /// Locales: en, pt-BR
      static func lastPurchaseOrder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("lastPurchaseOrder", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "lastPurchaseOrder"
        }

        return NSLocalizedString("lastPurchaseOrder", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: Last quotation
      ///
      /// Locales: en, pt-BR
      static func lastQuotation(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("lastQuotation", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "lastQuotation"
        }

        return NSLocalizedString("lastQuotation", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: Overview
      ///
      /// Locales: en, pt-BR
      static func homeTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("homeTitle", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "homeTitle"
        }

        return NSLocalizedString("homeTitle", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: Please try again later.
      ///
      /// Locales: en
      static func apiNotAvailable(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("apiNotAvailable", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "apiNotAvailable"
        }

        return NSLocalizedString("apiNotAvailable", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: Sum of an Hour
      ///
      /// Locales: en, pt-BR
      static func sumAnHour(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("sumAnHour", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "sumAnHour"
        }

        return NSLocalizedString("sumAnHour", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: Sum of an day
      ///
      /// Locales: en, pt-BR
      static func sumAnday(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("SumAnday", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "SumAnday"
        }

        return NSLocalizedString("SumAnday", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: Summation one month
      ///
      /// Locales: en, pt-BR
      static func sumMonth(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("SumMonth", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "SumMonth"
        }

        return NSLocalizedString("SumMonth", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: Total symbols
      ///
      /// Locales: en, pt-BR
      static func totalSymbols(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("totalSymbols", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "totalSymbols"
        }

        return NSLocalizedString("totalSymbols", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: Transfer coins from other platforms   to your bitcoin market wallet or   access the site and make a deposit.
      ///
      /// Locales: en, pt-BR
      static func messageHomeHeader(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("messageHomeHeader", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "messageHomeHeader"
        }

        return NSLocalizedString("messageHomeHeader", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: You are currently offline.
      ///
      /// Locales: en, pt-BR
      static func offline(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("offline", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "offline"
        }

        return NSLocalizedString("offline", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: You have no balance
      ///
      /// Locales: en, pt-BR
      static func titleHomeHeader(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("titleHomeHeader", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "titleHomeHeader"
        }

        return NSLocalizedString("titleHomeHeader", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: erro
      ///
      /// Locales: en, pt-BR
      static func error(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("error", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "error"
        }

        return NSLocalizedString("error", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: price: 
      ///
      /// Locales: en, pt-BR
      static func price(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("price", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "price"
        }

        return NSLocalizedString("price", tableName: "App", bundle: bundle, comment: "")
      }

      /// en translation: show details
      ///
      /// Locales: en, pt-BR
      static func showDetails(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("showDetails", tableName: "App", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "App", preferredLanguages: preferredLanguages) else {
          return "showDetails"
        }

        return NSLocalizedString("showDetails", tableName: "App", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
